import 'package:flutter/cupertino.dart';
import 'package:flutter_app_funandroid/config/router_config.dart';
import 'package:flutter_app_funandroid/generated/i18n.dart';
import 'package:flutter_app_funandroid/ui/widget/favourite_animation.dart';
import 'package:flutter_app_funandroid/config/resource_namager.dart';
import 'package:flutter_app_funandroid/config/router_config.dart';
import 'package:flutter_app_funandroid/model/article.dart';
import 'package:flutter_app_funandroid/provider/provider_widget.dart';
import 'package:flutter_app_funandroid/view_model/fa';